Firma.PortalWWW/Models/ErrorViewModel.cs
namespace Firma.PortalWWW.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Firma.PortalWWW/Controllers/AktualnoscController.cs
using Firma.Data.Data;
using Microsoft.AspNetCore.Mvc;
using Firma.PortalWWW.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Firma.Data.Data;

namespace Firma.PortalWWW.Controllers
{
    public class AktualnoscController : Controller
    {
        //private readonly ILogger<AktualnoscController> _logger;
        private readonly FirmaContext _context; // to jest DB

        public AktualnoscController(FirmaContext context)
        {
            _context = context;
        }
        public IActionResult Index(int id) //id kliknietej aktualnosci
        {
            ViewBag.ModelStrony =
            (
                from strona in _context.Strona
                orderby strona.Pozycja
                select strona
            ).ToList();
            ViewBag.ModelAktualnosci =
            (
                from aktualnosc in _context.Aktualnosc
                orderby aktualnosc.Pozycja
                select aktualnosc
            ).ToList();
            ViewBag.ModelInformacjeDodatkowe =
            (
                from strona in _context.Strona
                orderby strona.Pozycja
                select strona
            ).ToList();
            ViewBag.ModelKontakt =
            (
                from aktualnosc in _context.Aktualnosc
                orderby aktualnosc.Pozycja
                select aktualnosc
            ).ToList();
            ViewBag.ModelParametry =
            (
                from parametr in _context.Parametr
                orderby parametr.Pozycja
                select parametr
            ).ToList();
            //wyszukujemy aktualnosci o danym kliknietym ID
            var item = _context.Aktualnosc.Find(id);

            return View(item);
        }
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Firma.PortalWWW/Controllers/HomeController.cs
using Firma.PortalWWW.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Firma.Data.Data;

namespace Firma.PortalWWW.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly FirmaContext _context; // to jest DB

        // public HomeController(ILogger<HomeController> logger)
        // {
        //     _logger = logger;
        // }
        public HomeController(FirmaContext context)
        {
            _context = context;
        }

        public IActionResult Index(int? id) // identyfikator kliknietej strony w menu
        {
            //ViewBag to taki listonosz ktory przenosi dane miedzy controllerem a widokiem. Po kropce we ViewBagu mozna dowolnie nazwac zmienna
            ViewBag.ModelStrony =
            (
                from strona in _context.Strona
                orderby strona.Pozycja
                select strona
            ).ToList();
            ViewBag.ModelAktualnosci =
            (
                from aktualnosc in _context.Aktualnosc
                orderby aktualnosc.Pozycja
                select aktualnosc
            ).Take(3).ToList();
            // ).Take(3).ToList();   //TODO -> można ograniczyc aktualnosci np orderby id desc
            ViewBag.ModelInformacjeDodatkowe =
            (
                from strona in _context.Strona
                orderby strona.Pozycja
                select strona
            ).ToList();
            ViewBag.ModelKontakt =
            (
                from aktualnosc in _context.Aktualnosc
                orderby aktualnosc.Pozycja
                select aktualnosc
            ).ToList();
            ViewBag.ModelParametry =
            (
                from parametr in _context.Parametr
                orderby parametr.Pozycja
                select parametr
            ).ToList();
            //jezeli ktos wejdzie 1 raz do portalu to nie ma kliknietej wybranej strony i id = null -> wtedy wysiertla sie 1 strona
            if (id == null)
            {
                id = _context.Strona.First().IdStrony;
            }
            //odnajdujemy w DB strone o danym id
            var item = _context.Strona.Find(id);
            //i przekazujemy ją do widoku zeby widok ją wyswietlil
            return View(item);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Company()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View(); //widok będzie nazywał sie tak samo jak funkcja wiec mozna -> return View()
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Firma.PortalWWW/Views/Aktualnosc/Index.cshtml
@model Firma.Data.Data.CMS.Aktualnosc
@{
    ViewData["Title"] = @Model.LinkTytul;
}

<h1 class="header center orange-text">Aktualnosc: @Model.Tytul</h1>
<div class="row center">
    <h5 class="header col s12 light">@Model.Tresc</h5>
</div>

Firma.PortalWWW/Views/Home/Company.cshtml
@{
    ViewData["Title"] = "Company";
}
<h1 class="header center orange-text">About</h1>
<div class="row center">
    <h5 class="header col s12 light">Tu bedzie o firmie</h5>
</div>

Firma.PortalWWW/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}

<h1 class="header center orange-text">Kontakt</h1>
<div class="row center">
    <h5 class="header col s12 light">Jnfo kontaktowe</h5>
</div>

Firma.PortalWWW/Views/Home/Index.cshtml
@model Firma.Data.Data.CMS.Strona
@{
    ViewData["Title"] = @Model.LinkTytul;
}

<h1 class="header center orange-text">@Model.Tytul</h1>
<div class="row center">
    <h5 class="header col s12 light">@Model.Tresc</h5>
</div>

Firma.PortalWWW/Views/Shared/Aktualnosci.cshtml
@model IEnumerable<Firma.Data.Data.CMS.Aktualnosc>
<div class="section">

    <!--   Icon Section   -->
    @foreach (var item in Model)
    {
        <div class="col s12 m4">
            <div class="icon-block">
                <h2 class="center light-blue-text">
                    <i class="material-icons">flash_on</i>
                </h2>
                <h5 class="center"> @Html.ActionLink(item.LinkTytul, "Index", "Aktualnosc",
                                        new { id = item.IdAktualnosci }, null)</h5>
                <p class="light">@item.Tresc</p>
            </div>
        </div>
    }
</div>
<br><br>

Firma.PortalWWW/Views/Shared/InformacjeDodatkowe.cshtml
@model IEnumerable<Firma.Data.Data.CMS.Strona>

<h5 class="white-text">Informacje Dodatkowe</h5>
<ul>
    @foreach (var item in Model)
    {
        <li>@Html.ActionLink(item.LinkTytul, "Index", "Home", new {id=item.IdStrony},null)</li>
    
    }
</ul>

@* <li>@Html.ActionLink("Prywatność", "Privacy", "Home")</li> *@

Firma.PortalWWW/Views/Shared/Kontakt.cshtml
@model IEnumerable<Firma.Data.Data.CMS.Aktualnosc>

<h5 class="white-text">Connect</h5>
<ul>
    @foreach (var item in Model)
    {
        <li>@Html.ActionLink(item.LinkTytul, "Index", "Aktualnosc", new {id=item.IdAktualnosci},null)</li>
    }
</ul>

Firma.PortalWWW/Views/Shared/Odnosniki.cshtml
@model IEnumerable<Firma.Data.Data.CMS.Strona> 
<div class="nav-wrapper container">
    <a id="logo-container" href="#" class="brand-logo">Logo</a>
    <ul class="right hide-on-med-and-down">
        @foreach (var item in Model)
        {
            <li>@Html.ActionLink(item.LinkTytul, "Index", "Home", new {id=item.IdStrony},null)</li>
        }
        @* <li>@Html.ActionLink("Strona główna", "Index", "Home")</li> *@
        @* <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li> *@
        @* <li>@Html.ActionLink("O firmie", "Company", "Home")</li> *@
    </ul>

    <ul id="nav-mobile" class="sidenav">
        <li><a href="#">Navbar Link</a></li>
    </ul>
    <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
</div>

Firma.PortalWWW/Views/Shared/Parametry.cshtml
@model IEnumerable<Firma.Data.Data.CMS.Parametr>
@foreach (var item in Model)
{
    if (item.Nazwa.Equals("WSBname"))
    {
        <h5 class="white-text">@item.Tresc </h5>
    }
    else
    {
        <p class="grey-text text-lighten-4">@item.Tresc</p>
    }
    
}

Firma.PortalWWW/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title>Starter Template - Materialize</title>

    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="~/lib/materialize/css/materialize.min.css" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="~/lib/materialize/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>
<body>
<nav class="light-blue lighten-1" role="navigation">
    @await Html.PartialAsync("Odnosniki", (IEnumerable<Firma.Data.Data.CMS.Strona>)ViewBag.ModelStrony)
</nav>
<div class="section no-pad-bot" id="index-banner">
    <div class="container">
        @RenderBody()
    </div>
</div>


<div class="container">
    <div class="row">
        @await Html.PartialAsync("Aktualnosci", (IEnumerable<Firma.Data.Data.CMS.Aktualnosc>)ViewBag.ModelAktualnosci)
    </div>
</div>

<footer class="page-footer orange">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                @await Html.PartialAsync("Parametry", (IEnumerable<Firma.Data.Data.CMS.Parametr>)ViewBag.ModelParametry)


            </div>
            <div class="col l3 s12">
                @await Html.PartialAsync("InformacjeDodatkowe", (IEnumerable<Firma.Data.Data.CMS.Strona>)ViewBag.ModelInformacjeDodatkowe)
            </div>
            <div class="col l3 s12">
                @await Html.PartialAsync("Kontakt", (IEnumerable<Firma.Data.Data.CMS.Aktualnosc>)ViewBag.ModelKontakt)
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            Made by <a class="orange-text text-lighten-3" href="http://materializecss.com">Kacper</a>
        </div>
    </div>
</footer>


<!--  Scripts-->
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="../../bin/materialize.js"></script>
<script src="js/init.js"></script>

</body>
</html>